
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilterInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.TargetDataLine;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
/**
 *
 * @author chris
 */
public class Play extends javax.swing.JFrame {
    Properties p = new Properties();
    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
          p.setBackground(p.currBackground);
          p.setStroke(p.currStoke);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Main = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        PlayItem = new javax.swing.JMenu();
        PlayFiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        Main.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1464, Short.MAX_VALUE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        PlayItem.setText("Play");

        PlayFiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PlayFiles.setText("Read Files");
        PlayFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayFilesActionPerformed(evt);
            }
        });
        PlayItem.add(PlayFiles);

        jMenuBar1.add(PlayItem);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayFilesActionPerformed
        try {
            String gongFile ="RecordAudio.wav";
            InputStream in = new FileInputStream(gongFile);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(in);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
            p.text.check(1);
        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PlayFilesActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }
    class Properties {
        private Date time = new Date();
        private long currTime = setCurrTime(new Date());
        private long startTime = currTime;
        private long timeDiff;
        private Timings Ptimings= new Timings();
        private boolean isMoving = false;
        private boolean isClicked = false;
        private boolean canRecord = false;
        private Color currStoke = Color.BLACK;
        private Color currBackground = Color.WHITE;
        private boolean canDraw = true;
        private int segCounter =0;
        private int strokeCounter = 0;
        private int pages = 1;
        private int backgroundCounter = 0;
        private VoiceRecording vr;
        private int timeBreakCounter = 0;
        private Text text = new Text();
        private ArrayList<Long> Times = new ArrayList<>();
        private ArrayList<Long> timeBreaks = new ArrayList<>();
        private ArrayList<Point> seg = new ArrayList<>();
        private ArrayList<ArrayList<Point>> segments = new ArrayList<>();
        private boolean isVoiceRecording = false;
        private Properties TempProperties;
        private boolean playing = false;
        private String [] data;
        public void setMoving(boolean move){
            System.out.println("Moving");
            this.isMoving = move;
        }
        public void setClicked(boolean clicked){
            System.out.println("Clicked");
            this.isMoving = clicked;
        }
        public void setStroke(Color c){
            this.currStoke = c;
        }
        public void setBackground(Color c){
            Main.setBackground(c);
            this.currBackground = c;
        }
        public long setCurrTime(Date d){
            return currTime = d.getTime();
        }
        public void setTimeBreak(Long time){
            this.timeBreaks.add(time);
//             for(int i = 0; i < timeBreaks.size(); i++)
//                System.out.println("Timesbreaks("+i+"): " + this.timeBreaks.get(i));
                
        }
        public void setTimeDiff(){
            Date d = new Date();
            timeDiff = d.getTime() - getCurrTime();
            setTimes(timeDiff);
            setCurrTime(new Date()); 
        }
        public void setTimes(Long time){
            this.Times.add(time);
        }
        public boolean getDraw(){
            return canDraw;
        }
        public long getCurrTime(){
            return currTime;
        }
        public long getTimeDiff(){
            return timeDiff;
        }
        public boolean getVoiceRecording(){
            return isVoiceRecording;
        }
        public boolean getPlaying(){
            return playing;
        }
        public void draw(Graphics g){
            if(canDraw == true){
            g.setColor(currStoke);
            System.out.println(this.isClicked);
            System.out.println(this.isMoving);
            System.out.println("Drawing");
            System.out.println("draw Seg Counter: " + segCounter);
            g.drawLine(segments.get(segCounter).get(seg.size()-2).x,
                       segments.get(segCounter).get(seg.size()-2).y, 
                       segments.get(segCounter).get(seg.size()-1).x,
                       segments.get(segCounter).get(seg.size()-1).y);
            }
        }
        public void drawDot(Graphics g, Point point){
            g.setColor(currStoke); 
            g.fillRect(point.x, point.y, 1, 1);
        }
        public void createSegment(int index){
            ArrayList<Point> a = new ArrayList();
            seg = a;
            System.out.println("Size " + seg.size());
            segments.add(index, seg);
        }
        public void clearAll(){
            this.timeDiff= 0;
            this.seg.clear();
            this.segments.clear();
            this.segCounter=0;
            this.currStoke = Color.BLACK;
            this.setBackground(Color.WHITE);
            this.setCurrTime(new Date());
            this.Times.clear();
            this.timeBreakCounter = 0;
            this.timeBreaks.clear();
            this.clearScreen(Main.getGraphics());
        }
        public void record(){
            this.clearAll();
            this.canRecord = true;
        }
        public void InitVoiceRecord(){
            vr = new VoiceRecording();
        }
        public void newPage() throws IOException{
            text = new Text(pages);
            clearAll();
        }
        public void stopRecording(){
            isVoiceRecording = false;
             vr.finish();
        }
        public void recording(){
              // creates a new thread that waits for a specified
        Thread recorder = new Thread(new Runnable() {
            public void run(){
                 vr.start();
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
            }
        });
        recorder.start();
        }
        public void clearScreen(Graphics g){
            g.setColor(this.currBackground);
            g.fillRect(0,0, Main.getWidth(), Main.getHeight());
        }
        public void readData(String [] data, int page){
            int index = 0;
            int TempSegmentsIndex = -1;
            int TempSegIndex = -1;
            ArrayList<Long> TempTimes = new ArrayList<>();
            ArrayList<Long> TempTimeBreaks = new ArrayList<>();
            ArrayList<Point> TempSeg;
            ArrayList<ArrayList<Point>> TempSegments = new ArrayList<>();
            Color TempBackGround = Color.WHITE;
            Color TempStroke = Color.BLACK;
            String segmentDone = "-segmentDone-";
            String SegmentsDone = "-SegmentsDone-";
            String Segments = "-Segments-";
            String segs = "-segs-";
            String segsDone = "-segsDone-";
            String Times = "-Times-";
            String nextTime = "-nextTime-";
            String TimesDone = "-TimesDone-";
            String TimeDiff = "-TimeDiff-";
            String nextTimeDiff = "-nextTimeDiff-";
            String TimeDiffDone = "-TimeDiffDone-";
            String BackGround = "-BackGround-";
            String Stoke = "-Stoke-";
            String Finished = "-Finished-";
            while(index < data.length){
                System.out.println(data[index].trim());
                while(!data[index].trim().equals(SegmentsDone)){
                   System.out.println(data[index].trim());
                    if(data[index].trim().equals(Segments)){
                        index++;
                        TempSegmentsIndex++;
                        TempSeg = new ArrayList<>();
                        System.out.println(data[index].trim());
                        while(data[index].trim().equals(segs)){
                            index++;
                            TempSegIndex++;
                            String [] XY = data[index].trim().split(",");
                            Point point = new Point(Integer.parseInt(XY[0].trim()), Integer.parseInt(XY[1].trim()));
                            TempSeg.add(point);
                            index++;
                            System.out.println(data[index].trim());
                            if(data[index].trim().equals(segsDone)){
                               index++;
                               TempSegments.add(TempSeg);
                               TempSegIndex = 0;
                               if(data[index].trim().equals(segmentDone)){
                                   TempSegmentsIndex++;
                                   index++;
                               }
                            }
                        }
                    }
                }
                index++;
                //Where you left off reading times from file
                //System.out.println(data[index].trim());
                        if(data[index].trim().equals(Times)){
                             System.out.println("Comparar: " + data[index].trim());
                             index++;
                            while(!data[index].trim().equals("-TimesDone-")){
                                System.out.println(data[index].trim());
                                System.out.println("Time: " + data[index].trim());
                                TempTimes.add(Long.parseLong(data[index].trim()));
                                index++;
                                System.out.println("nextTime "+ data[index].trim());
                            if(data[index].trim().equals(nextTime))
                                index++;
                            }
                            
                        }
                        if(data[index].trim().equals(TimesDone)){
                            index++;
                            if(data[index].trim().equals(TimeDiff)){
                                while(!data[index].trim().equals("-TimeDiffDone-")){
                                    System.out.println("timediff "+data[index].trim());
                                    index++;
                                    System.out.println("Int: "+data[index].trim());
                                    TempTimeBreaks.add(Long.parseLong(data[index].trim()));
                                    index++;
                                    System.out.println("nextTime" + data[index].trim());
                                    if(data[index].trim().equals(nextTimeDiff)){
                                        if(data[index+1].trim().equals(TimeDiffDone)){
                                            System.out.println("done");
                                            index++;
                                        }
                                }
                                    if(data[index].trim().equals(TimeDiffDone)){
                                        System.out.println("Stay");
                            }
                        }
                            }
                        if(data[index].trim().equals(TimeDiffDone))
                                            index++;
                                    }
                        if(data[index].trim().equals(BackGround)){
                            index++;
                            String [] color = data[index].trim().split(",");
                            float [] c = Color.RGBtoHSB(Integer.parseInt(color[0]), Integer.parseInt(color[1]), Integer.parseInt(color[2]),null);
                   
                            TempBackGround = Color.getHSBColor(c[0], c[1], c[2]);
                            index++;
                        } 
                        if(data[index].trim().equals(Stoke)){
                            index++;
                            String [] color = data[index].trim().split(",");
                            float [] c = Color.RGBtoHSB(Integer.parseInt(color[0]), Integer.parseInt(color[1]), Integer.parseInt(color[2]),null);
                            TempStroke = Color.getHSBColor(c[0], c[1], c[2]);
                            index++;
                        } 
                        if(data[index].trim().equals(Finished)){
                            index++;
                        }
            }
            System.out.println("Reading Complete....");
            TempProperties = new Properties();
            TempProperties.currStoke = TempStroke;
            TempProperties.currBackground = TempBackGround;
            TempProperties.segments = TempSegments;
            System.out.println(TempSegments.get(0).get(0).x + "," +TempSegments.get(0).get(0).y);
            TempProperties.Times = TempTimes;
            System.out.println("Temp times: "+TempTimes.get(0));
            TempProperties.timeBreaks = TempTimeBreaks;
            System.out.println("Temp: " + TempProperties.currBackground);
            TempProperties.play(page);
        }
        public void play(){
            clearScreen(Main.getGraphics());
            System.out.println("Playing....");
            Timers timer = new Timers();
            timer.drawTimer.start();
            p.clearScreen(Main.getGraphics()); 
        }
        public void play(int pages){
            clearScreen(Main.getGraphics());
            System.out.println("Playing....");
            Timers timer = new Timers();
            timer.currpage = pages;
            timer.drawTimer.start();
            p.clearScreen(Main.getGraphics()); 
        }
        class Timers{
            Replay replay= new Replay(this,Ptimings);
            Timer drawTimer = new Timer(1,replay);
            Timer strokeTimer = new Timer(1,null);
            Timer backgroundTimer = new Timer(1,null);
            long drawCounter = 0;
            long strokeCounter = 0;
            long backgroundCounter = 0;
            int currpage = -1;
            long getDrawCounter(){
                System.out.println("Drawcounter: " + drawCounter);
                return drawCounter;
            }
            long getStrokeCounter(){
                return strokeCounter;
            }
             long getBackgroundCounter(){
                return backgroundCounter;
            }
        }
        class Timings{
            private long startTime = 0;
            private long backgroundCT = 0;
            private long strokeCT = 0;
            private ArrayList<Long> strokeTimes = new ArrayList<>();
            private ArrayList<Long> backgroundTimes= new ArrayList<>();
            public void setStartTime(long s){
                this.startTime = s;
            }
            
            public long setCurrTime(Date d){
            return d.getTime();
        }
            
            public void setTimeDiff(long currtime, ArrayList<Long> list){ 
                Date d = new Date();
                long ct = d.getTime();
                long timediff = d.getTime() - currTime;
                list.add(timediff);
                currtime = ct;
            } 
        }
        public class VoiceRecording{// record duration, in milliseconds
            static final long RECORD_TIME = 6000; // 1 minute
            // path of the wav file
            File wavFile = new File("RecordAudio.wav");
            // format of audio file
            AudioFileFormat.Type fileType = AudioFileFormat.Type.WAVE;
    
            // the line from which audio data is captured
            TargetDataLine line;

            AudioFormat getAudioFormat() {
                float sampleRate = 8000;
                int sampleSizeInBits = 16;
                int channels = 2;
                boolean signed = true;
                boolean bigEndian = true;
                AudioFormat format = new AudioFormat(sampleRate, sampleSizeInBits,channels, signed, bigEndian);
                return format;
            }
    /**
     * Captures the sound and record into a WAV file
     */
    void start() {
        try {
            AudioFormat format = getAudioFormat();
            DataLine.Info info = new DataLine.Info(TargetDataLine.class, format);
            // checks if system supports the data line
            if (!AudioSystem.isLineSupported(info)) {
                System.out.println("Line not supported");
                System.exit(0);
            }
            line = (TargetDataLine) AudioSystem.getLine(info);
            line.open(format);
            line.start(); // start capturingSystem.out.println("Start capturing..."); 
            AudioInputStream ais = new AudioInputStream(line);
            System.out.println("Start recording...");
            
            // start recording
            AudioSystem.write(ais, fileType, wavFile);
        } catch (LineUnavailableException ex) {
            ex.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }
    /**
     * Closes the target data line to finish capturing and recording
     */
            void finish() {
                line.stop();
                line.close();
                System.out.println("Finished");
            }
        }
        class Replay implements ActionListener{
            long t = 0;
            int Bseg = 0;
            int Sseg = 0 ;
            int times = 0;
            int tbreaks = 0;
            int sc = 1;
            int bc = 1;
            int currpage = -1;
            String file = "";
            Graphics g = Main.getGraphics();
            Timers timers;
            Timings replayTimings;
            Replay(Timers t, Timings tm){
                timers= t;
                if(t == null)
                    System.out.println("t is null");
                replayTimings = tm;
            }
            public String getFile(){
                return file;
            }
            @Override
            public void actionPerformed(ActionEvent ae) {
                Main.setBackground(currBackground);
                System.out.print("Color: " + currBackground);
                g.setColor(currStoke);
                 if(Bseg < segments.size()){
                   System.out.println("Bseg: " + Bseg +" size: " + segments.get(Bseg).size());
                   if(Sseg+1 < (segments.get(Bseg).size())){
                       System.out.println("P times " + Times.get(this.times));
                        if(timers.getDrawCounter() == Times.get(this.times)){
                            System.out.println("P times " + Times.get(this.times));
                            g.drawLine(segments.get(Bseg).get(Sseg).x,
                               segments.get(Bseg).get(Sseg).y,
                               segments.get(Bseg).get(Sseg+1).x, 
                               segments.get(Bseg).get(Sseg+1).y);
                            timers.drawTimer.restart();
                            timers.drawCounter=0;
                            Sseg+=1;
                            this.times++;
                    }
                }
               else{
                   Bseg+=1;
                   Sseg = 0;
                   timers.drawCounter=0;
                 }
                }
                if(Bseg == segments.size()){
                    this.Bseg = 0;
                    this.Sseg = 0;
                    this.t = 0;
                    this.timers.drawTimer.stop();
                    playing = false;
                    if(timers.currpage != -1){
                      
                        try {
                            text.check(timers.currpage+1);
                        } catch (IOException ex) {
                            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
                        }
                       
                    }
                }
            this.timers.drawCounter++;
//            this.bc++;
//            this.sc++;
            }
        }
        public class Text {
            DataOutputStream dos;
            String [] file;
            Reading reading;
            boolean canPlay = true;
            public void check (int fileName) throws FileNotFoundException, IOException{
                    if(new File(Integer.toString(fileName)).exists()){
                        System.out.println("File exist");
                        reading = new Reading(new FileInputStream(Integer.toString(fileName)));
                        System.out.println("Reading...........................");
                        reading.read();
                        file = reading.getText().split(" ");
                        System.out.println(file[0]);
                        reading.close();
                        readData(file, fileName);
                    }
                    else{
                      System.out.println("File Doesn't exist");
                    } 
                }
            public Text(){    
            }
            public Text(int num) throws FileNotFoundException, IOException{
                dos = new DataOutputStream(new FileOutputStream(Integer.toString(pages)));
                int segTempCount =0;
                int segmentsTempCount =0;
                while(segmentsTempCount < segments.size()){
                    dos.writeUTF("-Segments- ");
                    System.out.println("Segments");
                    while(segTempCount < segments.get(segmentsTempCount).size()){
                        dos.writeUTF("-segs- ");
                        System.out.println("segs");
                        String points = segments.get(segmentsTempCount).get(segTempCount).x + ","+segments.get(segmentsTempCount).get(segTempCount).y + " ";
                        dos.writeUTF(points);
                        System.out.println(points);
                        segTempCount++;
                    }
                    System.out.println("segsDone");
                    dos.writeUTF("-segsDone- ");
                    segTempCount = 0;
                    segmentsTempCount++;
                    dos.writeUTF("-segmentDone- ");
                }
                dos.writeUTF("-SegmentsDone- ");
                dos.writeUTF("-Times- ");
                int timesIndex = 0;
                while(timesIndex <Times.size()){
                    dos.writeUTF(Long.toString(Times.get(timesIndex))+ " ");
                    dos.writeUTF("-nextTime- ");
                    timesIndex++;
                }
                dos.writeUTF("-TimesDone- ");
                timesIndex = 0;
                dos.writeUTF("-TimeDiff- ");
                while(timesIndex < timeBreaks.size()){
                    dos.writeUTF(Long.toString(timeBreaks.get(timesIndex))+ " ");
                    dos.writeUTF("-nextTimeDiff- ");
                    timesIndex++;
                }
                dos.writeUTF("-TimeDiffDone- ");
                dos.writeUTF("-BackGround- ");
                dos.writeUTF(currBackground.getRed()+ ","+currBackground.getGreen()+","+currBackground.getBlue()+ " ");
                dos.writeUTF("-Stoke- ");
                dos.writeUTF(currStoke.getRed()+ ","+currStoke.getGreen()+","+currStoke.getBlue()+ " ");
                dos.writeUTF("-Finished- ");
                dos.flush();
                dos.close();
                Reading reading = new Reading(new FileInputStream(Integer.toString(pages)));
                
                pages+=1;
            }
            public class Reading extends FilterInputStream {
            private String message = "";
            public Reading(InputStream in) throws IOException{
            super(in);
        }
        @Override
        public int read() throws IOException{
            String temp = "";
            int value;
            String FirstLetter = "";
            int counter = 0;
            while(((value = in.read()) != -1)){
                if(counter == 0)
                    in.skip(1);
                message += (char)value;
                counter++;
            }
            temp += message;
            message = temp;

        return 0;

        }
        public String getText(){
            return message;
        }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JMenuItem PlayFiles;
    private javax.swing.JMenu PlayItem;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
